# Generated by Django 3.1.6 on 2021-02-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210219_0439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
